### ISSUE TITLE
[Improvement] Documentation

### ISSUE THREAD

**Issue by LegitCamper** [rizki4106/netrade#4]
So far while trying out this library I have had a great time. Since this library relies so heavily on the images generated; you should include a code snippet of how you generate your Charts and Candles. With this improvement, anyone could pick up the library and use yfinance for example to train their own model very easily

**Comment by LegitCamper** [comment]
I also get this runtime error with the documented Test

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [28, 3, 2, 2], but got 5-dimensional input of size [1, 1, 4, 224, 224] instead

**Comment by rizki4106** [comment]
I'll post article that how do i create chart and candle stick image very soon. but if you use your own way to generate image make sure you are not unsqueeze the image dimention because it's already handled by this library. The desire input image shape for chart pattern is `(batch size, channel, height, width)` and it's same as candle stick image shape. again image shape is **already handled by his library** so you don't have to worry about it what you need to do just create image transformer to turn image into torch tensor. I'll post about how do i generate image very soon and notify you

**Comment by rizki4106** [comment]
Hi now you can create the image data from real - time data, here's the step -> [create chart and candle stick image from real-time data](https://github.com/rizki4106/netrade#real-time-data). I'll create an article how this helper works soon, i hope it can solve your problem
